"""empty message

Revision ID: 838bf5c3c570
Revises: 
Create Date: 2024-09-27 15:25:11.882112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '838bf5c3c570'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_deadline'), ['deadline'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_name'), ['name'], unique=True)

    op.create_table('web_site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('web_site', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_web_site_url'), ['url'], unique=False)

    op.create_table('interval',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_ids', sa.String(length=64), nullable=False),
    sa.Column('allowed_websites', sa.String(length=1024), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'INITIATED', 'FINISHED', name='intervalstatus'), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interval', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interval_allowed_websites'), ['allowed_websites'], unique=False)
        batch_op.create_index(batch_op.f('ix_interval_start_time'), ['start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_interval_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_interval_task_ids'), ['task_ids'], unique=False)

    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('duration_worked_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('NOT_COMPLETED', 'IN_PROGRESS', 'COMPLETED', name='taskstatus'), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_duration_seconds'), ['duration_seconds'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_duration_worked_seconds'), ['duration_worked_seconds'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_status'))
        batch_op.drop_index(batch_op.f('ix_task_name'))
        batch_op.drop_index(batch_op.f('ix_task_duration_worked_seconds'))
        batch_op.drop_index(batch_op.f('ix_task_duration_seconds'))

    op.drop_table('task')
    with op.batch_alter_table('interval', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interval_task_ids'))
        batch_op.drop_index(batch_op.f('ix_interval_status'))
        batch_op.drop_index(batch_op.f('ix_interval_start_time'))
        batch_op.drop_index(batch_op.f('ix_interval_allowed_websites'))

    op.drop_table('interval')
    with op.batch_alter_table('web_site', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_web_site_url'))

    op.drop_table('web_site')
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_name'))
        batch_op.drop_index(batch_op.f('ix_project_deadline'))

    op.drop_table('project')
    # ### end Alembic commands ###
